name: Checkmarx Scan

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "qa" ]
  push:
    branches: [ "main", "qa" ]
  schedule:
    - cron: '30 9 * * 6'  # 3:30 AM Mexico time

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scans:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: write # only required for a private repository by github/codeql-action/upload-sarif
      pull-requests: write # for checkmarx/ast-github-action to create a PR comment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # This step checks out a copy of your repository.
      - name: Checkout repository
        uses: actions/checkout@v4
      # This step creates the Checkmarx One scan
      - name: Checkmarx One scan
        uses: checkmarx/ast-github-action@main
        with:
          project_name: ${{ github.repository }}
          cx_tenant: Xpertal
          base_uri: https://ast.checkmarx.net
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          #cx_client_id: testingkey1
          #cx_client_secret: testingkey123123122a4eQ
          additional_params: "--report-format pdf,sarif --output-path . --output-name GitPruebas --report-pdf-options sast,sca,iac-security --threshold 'sast-high=100;sca-high=100;iac-security=100;api-security=100' --filter 'state=CONFIRMED;TO_VERIFY' --scs-engines scorecard --scs-repo-url https://github.com/EricGarzaXpertal/GitPruebas.git --scs-repo-token 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"

      - name: Upload SAST PDF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Checkmarx SAST Report
          path: GitPruebas.pdf
 
      - name: Upload SARIF to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: GitPruebas.sarif
